version: '2'
services: 
  postgres: 
    image:  ds-9101aa230624:8083/devopscoe/dockercompose_postgres:61
    hostname: mypostgres
    
# Service name
  tomcat1: 
    image:  ds-9101aa230624:8083/devopscoe/dockercompose_tomcat:61
    links: 
      - postgres
    hostname: web1
    environment:
      - JDBC_URL="jdbc:postgresql://postgres:5432/UserDB"

  tomcat2: 
    image:  ds-9101aa230624:8083/devopscoe/dockercompose_tomcat:61
    links: 
      - postgres
    hostname: web2
    environment:
      - JDBC_URL="jdbc:postgresql://postgres:5432/UserDB"

  nginx: 
    image:  ds-9101aa230624:8083/devopscoe/dockercompose_nginx:61
    ports: 
        - "80"
    links: 
      - tomcat1
      - tomcat2
    environment:
      - WEB_SERVERS=tomcat1,tomcat2

